In [2]:
import numpy as np


In [5]:
np.eye(4)

# 4 * 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:


# wrong one

np.zeros(5) 



array([0., 0., 0., 0., 0.])

In [10]:

# correct method

np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.full((4,6),-4)

array([[-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4]])

In [19]:
a = np.array([[1,2],[4,9]])
b = np.array([[4,-1],[0,3]])
c = np.array([[1,2],[1,9],[-4,-2]])


scalar_a = 7*a
print(scalar_a)

scalar_b = 17*b
print(scalar_b)

scalar_c = -4*c
print(scalar_c)

consolidated_matrix = scalar_a + scalar_b
consolidated_matrix

[[ 7 14]
 [28 63]]
[[ 68 -17]
 [  0  51]]
[[ -4  -8]
 [ -4 -36]
 [ 16   8]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 